name: CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'dev'
        description: The environment to deploy to
        type: choice
        options:
          - dev
  push:
    tags:
      - 'v*.*.*' # e.g. v1.2.3, v1.2.3-env

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV and TAG variables
        run: |
          EVENT_NAME="${{ github.event_name }}"

          if [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)

            echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
            echo "TAG=${SHORT_SHA}" >> $GITHUB_ENV

          elif [[ "$EVENT_NAME" == "push" ]]; then
            RAW_TAG="${{ github.ref_name }}"
            STRIPPED_TAG="${RAW_TAG#v}"
            ENV_SUFFIX=$(echo "$STRIPPED_TAG" | cut -d '-' -f2)

            if [[ -z "$ENV_SUFFIX" ]]; then
              ENV="prod"
            else
              ENV="$ENV_SUFFIX"
            fi

            echo "ENV=$ENV" >> $GITHUB_ENV
            echo "TAG=$STRIPPED_TAG" >> $GITHUB_ENV

          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '22.x'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Demo
        run: |
          echo Env = ${{ env.ENV }}
          echo Tag = ${{ env.TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build devops app
        run: pnpm -w build
        env:
          ENVIRONMENT: ${{ env.ENV }}
          IMAGES_TAG: ${{ env.TAG }}

      - name: Deploy devops app #TODO: need to login to k8s first
        run: pnpm -w k8s build # change to deploy --include devops
        env:
          ENVIRONMENT: ${{ env.ENV }}
          IMAGES_TAG: ${{ env.TAG }}